name: GH-Pages
on:
  push:
    branches:
      - main
      - master
      - development

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./example
      - name: Build Web
        run: flutter build web --release --source-maps --base-href /s_design/
        working-directory: ./example
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
